name: Pipeline Aula 
 
on: 
  push 
 
jobs: 
  teste: 
    runs-on: ubuntu-latest 
 
    steps: 
      - uses: actions/checkout@v4 
 
      - name: Mostrar mensagem 
        run: echo "Pipeline executado com sucesso!"
        
      - name: Mostrar HTML 
        run: cat index.html   

      - name: Existe index.html? 
        run: |
          if [ -f "index.html" ]; then
            echo "O arquivo index.html existe."
          else
            echo "O arquivo index.html não existe."
          fi

      - name: Listar arquivos 
        run: ls -la

      - name: Mostrar conteúdo do diretório 
        run: ls -R  

